language: python

python: 3.7

install:
  - pip3 install --upgrade pip build wheel


jobs:
  include:
    - stage: build
      script: python3 -m build --outdir build .

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file: build/*.whl
  skip_cleanup: true
  on:
    tags: true
